### ISSUE TITLE
Consider BPL_SPRING_CLOUD_BINDINGS_ENABLED at build time

### ISSUE THREAD

**Issue by jreznot** [paketo-buildpacks/spring-boot#118]
## What happened?

As far as I see BPL_SPRING_CLOUD_BINDINGS_ENABLED is not considered during build time.
I want to build images without spring-cloud-bindings at all.

It would be great if `BPL_SPRING_CLOUD_BINDINGS_ENABLED = false` remove spring-cloud-bindgings from the resulting image.

Gradle configuration:
```
plugins {
    id 'org.springframework.boot' version '2.5.5'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
}

test {
    useJUnitPlatform()
}

bootBuildImage {
    environment = ['BPL_SPRING_CLOUD_BINDINGS_ENABLED' : 'false']
}
```

Log output for `gradle bootBuildImage`:
```
    [creator]       Launch Helper: Contributing to layer
    [creator]         Creating /layers/paketo-buildpacks_spring-boot/helper/exec.d/spring-cloud-bindings
    [creator]       Spring Cloud Bindings 1.8.0: Contributing to layer
    [creator]         Downloading from https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.8.0/spring-cloud-bindings-1.8.0.jar
    [creator]         Verifying checksum
    [creator]         Copying to /layers/paketo-buildpacks_spring-boot/spring-cloud-bindings
```

[striking-phoenix.zip](https://github.com/paketo-buildpacks/spring-boot/files/7250673/striking-phoenix.zip)

**Comment by dmikusa-pivotal** [comment]
>It would be great if BPL_SPRING_CLOUD_BINDINGS_ENABLED = false remove spring-cloud-bindgings from the resulting image.

This is the expected behavior. Env variables that start with `BPL_` are only applied at run or launch time (`L` is for launch). 

What is your use case for not including the bindings? The JAR is pretty small. Is it breaking something or causing problems?

Thanks

**Comment by jreznot** [comment]
> What is your use case for not including the bindings? The JAR is pretty small. Is it breaking something or causing problems?

I just don't want to have this moving part in my Docker images, I consider it one more dependency that I do not control. And if I do not use it why should I want to include it?

**Comment by dmikusa-pivotal** [comment]
OK, thanks for the feedback. I can appreciate your use case, it seems reasonable to me and something that we can do.

Being transparent, the use case is more of a cosmetic change and it's not something that I can prioritize highly at the moment, but given that we have other very similar features in other buildpacks, this would be an excellent opportunity if you or someone else is looking to contribute and submit a PR.

If someone were to submit a PR, I could certainly prioritize review & merging. Thanks.

**Comment by dmikusa-pivotal** [comment]
This has been implemented and should be available in the latest buildpack versions. The documentation had some issues and I filed https://github.com/paketo-buildpacks/spring-boot/pull/200 to get those cleaned up. The behavior in the buildpack is correct though.
