### ISSUE TITLE
Spring Cloud reference in an app that doesn't use Spring Cloud

### ISSUE THREAD

**Issue by snicoll** [paketo-buildpacks/spring-boot#12]
I have this vanilla Spring Boot app with only `spring-boot-starter-web` and I am building an image for it. 

This is what I get on startup with no customisation at all:

```
Container memory limit unset. Configuring JVM for 1G container.
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=88499K -XX:ReservedCodeCacheSize=240M -Xss1M -Xmx448076K (Head Room: 0%, Loaded Class Count: 13211, Thread Count: 250, Total Memory: 1.0G)
Adding 127 container CA certificates to JVM truststore
Spring Cloud Bindings Boot Auto-Configuration Enabled

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.2.RELEASE)

```

I find `Spring Cloud Bindings Boot Auto-Configuration Enabled` a bit odd. The unqualified `Boot` part seems unnecessary to me as the concept of Auto-Configuration is a concept that goes beyond Spring Boot itself.  If I understood what this does, "Spring Cloud Bindings Auto-Configuration Enabled" looks a better message to me.

That said, I find it a little bit confusing that an app that doesn't use Spring Cloud at all has such a message on startup. Thoughts?

**Comment by nebhale** [comment]
@snicoll the buildpack automatically puts Spring Cloud Bindings onto an application's Class-Path to enable auto-reconfiguration of bound services, if they exist, explaining why you're seeing this even though your application doesn't explicitly have Spring Cloud within it.

```
Paketo Spring Boot Buildpack 2.4.1
  https://github.com/paketo-buildpacks/spring-boot
  Build Configuration:
    $BP_BOOT_NATIVE_IMAGE                  the build to create a native image (requires GraalVM)
    $BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS  the arguments to pass to the native-image command
  Launch Configuration:
    $BPL_SPRING_CLOUD_BINDINGS_ENABLED     whether to auto-configure Spring Boot environment properties from bindings
  Creating slices from layers index
    dependencies
    spring-boot-loader
    snapshot-dependencies
    application
  Web Application Type: Contributing to layer
    Reactive web application detected
    Writing env.launch/BPL_JVM_THREAD_COUNT.default
  Spring Cloud Bindings 1.4.0: Contributing to layer
    Reusing cached download from buildpack
    Copying to /layers/paketo-buildpacks_spring-boot/spring-cloud-bindings
    Writing profile.d/spring-cloud-bindings.sh
  4 application slices
  Image labels:
    org.opencontainers.image.title
    org.opencontainers.image.version
    org.springframework.boot.spring-configuration-metadata.json
    org.springframework.boot.version
```

As a general rule we want to be very explicit when

1.  We add something to a user's application
1.  We activate the contributed behavior at launch time

However, Boot auto-configuration is a bit of an outlier from our normal integrations in that, us enabling our functionality **doesn't** mean that anything will happen in the user's application (i.e. no services are bound).  @snicoll do you have something more accurate that you'd like to see printed for this particular case?  @ekcasey Any thoughts on better wording here?

**Comment by snicoll** [comment]
Thanks for the feedback @nebhale 

> However, Boot auto-configuration is a bit of an outlier from our normal integrations in that, us enabling our functionality doesn't mean that anything will happen in the user's application (i.e. no services are bound)

Yeah, exactly. That's not compliant with an auto-configuration (it sits there and will do something only if it has to) but I understand why you'd want to let users know that something has been enabled (especially when that's the default behaviour). 

>  @snicoll do you have something more accurate that you'd like to see printed for this particular case?

A gist of that discussion would be better than the current form IMO. Something that states that service bindings will be taken into account if they exist sounds less assertive than the current form.

**Comment by snicoll** [comment]
I've also noticed (after raising this issue) that the build pack adds an extra layer with a jar that performs that binding operation. From the perspective, I wonder if disabling this feature by default was considered.

**Comment by nebhale** [comment]
The new message is:

> `Spring Cloud Bindings Enabled`

We did evaluate whether to enable this by default and opted to do so simply because it's only of the most widely used integrations in the previous generation of the buildpack.  There's been suggestions that once some of the new Spring Boot 2.4 "Properties from ConfigMap" functionality is in place, that we might want to move this entire integration out of the buildpack and into platforms, so until then we're going to defer any significant changes to the default behavior.

Resolved by https://github.com/paketo-buildpacks/spring-boot/commit/b7b14b41fc524ecdb69bd284bb41cec3fb25172e

**Comment by philwebb** [comment]
I wonder if we should expand the message a bit to "Spring Cloud Native Buildpack Bindings Enabled"? It's a bit more verbose, but not too bad and it makes it a bit clearer that it's "Spring _Cloud Native_", and not directly tied directly to the other `spring-cloud` projects.

**Comment by nebhale** [comment]
@philwebb It is a [Spring Cloud project](https://github.com/spring-cloud/spring-cloud-bindings).

**Comment by philwebb** [comment]
I know it's the `spring-cloud` organization, but I'm worried that using the term "Spring Cloud" without more context brings a certain number of expectations. Specifically, if you look at the [Spring Cloud Project Page](https://spring.io/projects/spring-cloud) they point out configuration, service registration, routing, load balancing, circuit breakers etc. I just don't want to cause confusion with people thinking that the buildpack is adding more patterns to their code than it actually is.

I think if we expand it to "Cloud Native Buildpacks" it'll just help people understand that it's a very focused library that's specifically designed to map the Cloud Native Binding Spec onto Spring Applications. The [POM file](https://github.com/spring-cloud/spring-cloud-bindings/blob/395a52217be09b2828e216b372cea7dfe3b0c803/pom.xml#L11) itself uses "Spring Cloud Cloud Native Buildpacks Bindings" as the project name (although I think we can safely drop one of the "clouds" for the message).
