### ISSUE TITLE
Checksum for spring-cloud-bindings-1.8.0 has changed in spring-repo and no longer matches the one announced

### ISSUE THREAD

**Issue by okrische** [paketo-buildpacks/spring-boot#172]
I am  using Paketo Spring Boot Buildpack 5.3.0

Yesterday my build worked. Now it doesnt. It fails with:

`sha256 for /tmp/c75ef3152817c28c7049d7e0052dfba3ed461a7151984e594b656c0be927888e/spring-cloud-bindings-1.8.0.jar 38657efbee82aaf69ea4998d5839b701173b8ccd01db0f97c3a16f86b2436bf7 does not match expected c75ef3152817c28c7049d7e0052dfba3ed461a7151984e594b656c0be927888e
`

As far as i can see, buildpack.toml is announcing the checksum `c75ef3152817c28c7049d7e0052dfba3ed461a7151984e594b656c0be927888e` for spring-cloud-bindings-1.8.0.jar

However, that jar may have been changed today, just 2 hours ago.

* https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.8.0/

The new checksum is:

krische@ds0093:~/Downloads$ sha256sum spring-cloud-bindings-1.8.0.jar
38657efbee82aaf69ea4998d5839b701173b8ccd01db0f97c3a16f86b2436bf7  spring-cloud-bindings-1.8.0 (1).jar

I wonder what happened there. Anyone knows who can re-create the original jar again?

**Comment by TomBeckett** [comment]
Same issue here, started within the last hour

**Comment by okrische** [comment]
And may have changed again. Oh this smells like trouble.

`krische@ds0093:~$ wget -qO - https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.8.0/spring-cloud-bindings-1.8.0.jar | sha256sum
fc375ad0e8a7a4f6aa295445cd9d0b1b859498282c86ce3db019bef742fdbd7a`

**Comment by okrische** [comment]
https://github.com/spring-cloud/spring-cloud-bindings/issues/61

**Comment by okrische** [comment]
They restored the old JAR for now (though, the sources jar may still be wrong). In any ways, seems to work again.

**Comment by dmikusa-pivotal** [comment]
Sorry about this.

We were able to restore the jar, but not the source jar. For buildpacks, this doesn't matter as they don't use the source jar. If you are pulling this dependency with Maven and it is causing issues (cause the source jar isn't correct), you can upgrade to 1.8.1 which should be correct. It is the same version with one bug fix to include support for some missing properties with Spring Security OAuth2 bindings.
