### ISSUE TITLE
Conditionally Add Spring Cloud Bindings

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/spring-boot#215]
## What happened?

If a user has Spring Cloud Bindings in their app, the buildpack will try to add it also and it creates problems. The buildpack should inspect the app to see if Spring Cloud Bindings is present and if present do nothing. If it's not present, it should install it.

This makes it easier if a user wants to control the version of SCB or create their own fork of SCB.

**Comment by pivotal-david-osullivan** [comment]
Closing this one as @anthonydahanne resolved in #318
