### ISSUE TITLE
Buildpack doesn't resolve correct ApplicationType

### ISSUE THREAD

**Issue by SchillingSebastian** [paketo-buildpacks/spring-boot#334]
Hey there 👋 
I have a fairly basic Kotlin Spring Boot 3 Application which has a `implementation("org.springframework.boot:spring-boot-starter-web")`dependency and a `@RestController` which just returns a String.
If I now run `bootBuildImage` I see the following lines
```
[creator]       Web Application Type: Contributing to layer
[creator]         Non-web application detected
[creator]         Writing env.launch/BPL_JVM_THREAD_COUNT.default
```
The `BPL_JVM_THREAD_COUNT` is then set to 50.
I would have expected it to stay at the default which is 250.
## Expected Behavior

The `BPL_JVM_THREAD_COUNT` is set to 250 and the a `Servlet web application detected` line in the log.
## Current Behavior

The buildpack logs `Non-web application detected` and sets `BPL_JVM_THREAD_COUNT` to 50.
## Steps to Reproduce

```Kotlin
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class SpringBuildpacksDemoApplication

fun main(args: Array<String>) {
    runApplication<SpringBuildpacksDemoApplication>(*args)
}
```

```Kotlin
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

@RestController()
@RequestMapping("hello")
class HelloController {

    @GetMapping
    fun getHello(): String{
        return "Hello 👋"
    }
}
```

```Kotlin
plugins {
    id("org.springframework.boot") version "3.0.4"
    id("io.spring.dependency-management") version "1.1.0"
    kotlin("jvm") version "1.7.22"
    kotlin("plugin.spring") version "1.7.22"
}

group = "de.s7g"
version = "0.1"
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "17"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

```

Then run `bootBuildImage` and observe the logs/startup of the container.

I am running everything on an Macbook M1 Pro
## Motivations

I was playing around with a minimal Spring Boot 3 web app and compared the build process of `bootBuildImage` with a large Spring Boot 2.7.X app. 
On the 'older app' the correct application type was detected.

**Comment by dmikusa** [comment]
The code looks through for some specific class files. It would only use `Non-web application detected` if it didn't find any of those classes.

1. It checks for `org.springframework.web.reactive.DispatcherHandler`. If it's there and it doesn't find `org.springframework.web.servlet.DispatcherServlet` or `org.glassfish.jersey.servlet.ServletContainer`, then it returns Reactive & 50 threads.
2. It then checks to make sure `javax.servlet.Servlet` and `org.springframework.web.context.ConfigurableWebApplicationContext` are present. If both are present, then it will return Servlet & 250 threads.
3. If either of `javax.servlet.Servlet` or `org.springframework.web.context.ConfigurableWebApplicationContext` are missing, it returns a non-webapp and 50 threads.

3.) must be what's happening with your app.

Can you confirm you have those classes present on the classpath?

**Comment by SchillingSebastian** [comment]
Okay I did do a simple "Lookup Classes" in IntelliJ. 
In my SpringBoot 3 app I have no `javax.servlet.Servlet` present, but I have the newer `jakarta.servlet.Servlet`. 
As for the `ConfigurableWebApplicationContext`: It is present in both the "old" 2.7.X and my 3.0.X.

I hope this is sufficient!
