### ISSUE TITLE
The locale setting never takes effect

### ISSUE THREAD

**Issue by GeTOUO** [paketo-buildpacks/spring-boot#389]
After the project is run as docker, Chinese always show a question mark when the console outputs：

![image](https://github.com/paketo-buildpacks/spring-boot/assets/26786920/070752a4-44a2-4c95-9a26-6799d5bdb64b)

Here is my code：

![image](https://github.com/paketo-buildpacks/spring-boot/assets/26786920/ca0c23de-7b5a-4aac-aa6b-067f42422186)

project info is:

spring-boot 3.1.1, jdk17

I've tried a lot of settings。The build configuration is now as follows:

```
    <properties>
        <!-- zh_CN.UTF-8, UTF-8, en_US.UTF-8 -->
        <locale.value>zh_CN.utf-8</locale.value>
        <java.version>17</java.version>
        ...
    </properties>
```

```
                    ...
                    <image>
                        <env>
                            <BPE_DELIM_JAVA_TOOL_OPTIONS xml:space="preserve"> </BPE_DELIM_JAVA_TOOL_OPTIONS>
                            <BPE_APPEND_JAVA_TOOL_OPTIONS>-Dfile.encoding=UTF-8</BPE_APPEND_JAVA_TOOL_OPTIONS>
                            <BPE_APPEND_JAVA_TOOL_OPTIONS>-Dsun.jnu.encoding=UTF-8</BPE_APPEND_JAVA_TOOL_OPTIONS>
                            <!-- 容器语言 -->
                            <!-- https://stackoverflow.com/questions/71699595/how-to-change-docker-image-built-with-spring-boot-maven-plugin-env-from-posix-to/71710785 -->
                            <BPE_LANG>${locale.value}</BPE_LANG>
                            <BPE_LC_ALL>${locale.value}</BPE_LC_ALL>
                            <BPE_LC_CTYPE>${locale.value}</BPE_LC_CTYPE><!--LANGUAGE=en_US:en-->
                            <BPE_LANGUAGE>zh_CN:zh</BPE_LANGUAGE><!--LANGUAGE=en_US:en-->
                            <!-- Build a native image -->
                            <!--<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>-->
                            <!-- 禁用 CPU 优化 -->
                            <!-- https://github.com/spring-projects/spring-boot/issues/36576 -->
                            <!--<BP_NATIVE_IMAGE_BUILD_ARGUMENTS>-march=compatibility</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>-->
                            <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                                <!-- -H:+IncludeAllLocales-->
                                -Duser.country=CN -Duser.language=zh -H:IncludeLocales=fr,en,it,en
                                -H:+AddAllCharsets
                            </BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                        </env>
                    </image>
                    ...

```

build:

`mvn spring-boot:build-image -Pnative`

building:

> [INFO] --- spring-boot-maven-plugin:3.1.1:build-image (default-cli) @ authorization-server ---
> [INFO] Building image 'docker.io/library/authorization-server:1.0-SNAPSHOT'
> [INFO]
> [INFO]  > Pulling builder image 'docker.io/paketobuildpacks/builder:tiny' 100%
> [INFO]  > Pulled builder image 'paketobuildpacks/builder@sha256:1a59354925fcb7ba54744b8017630c97c2b035e1a9e19309330557b9c66bfc2c'
> [INFO]  > Pulling run image 'docker.io/paketobuildpacks/run:tiny-cnb' 100%
> [INFO]  > Pulled run image 'paketobuildpacks/run@sha256:adf913cf28031f2090aeaedac65edb36f2987d81a23a8dffab5ea18ca216c94c'
> [INFO]  > Executing lifecycle version v0.16.5
> [INFO]  > Using build cache volume 'cache-authorization-server.build'
> [INFO]
> [INFO]  > Running creator
> [INFO]     [creator]     ===> ANALYZING
> [INFO]     [creator]     Restoring data for SBOM from previous image
> [INFO]     [creator]     ===> DETECTING
> [INFO]     [creator]     7 of 15 buildpacks participating
> [INFO]     [creator]     paketo-buildpacks/ca-certificates       3.6.3
> [INFO]     [creator]     paketo-buildpacks/bellsoft-liberica     10.2.6
> [INFO]     [creator]     paketo-buildpacks/syft                  1.32.1
> [INFO]     [creator]     paketo-buildpacks/executable-jar        6.7.4
> [INFO]     [creator]     paketo-buildpacks/spring-boot           5.26.1
> [INFO]     [creator]     paketo-buildpacks/native-image          5.12.1
> [INFO]     [creator]     paketo-buildpacks/environment-variables 4.5.3
> [INFO]     [creator]     ===> RESTORING
> [INFO]     [creator]     Restoring metadata for "paketo-buildpacks/ca-certificates:helper" from app image
> [INFO]     [creator]     Restoring metadata for "paketo-buildpacks/bellsoft-liberica:native-image-svm" from cache
> [INFO]     [creator]     Restoring metadata for "paketo-buildpacks/syft:syft" from cache
> [INFO]     [creator]     Restoring metadata for "paketo-buildpacks/native-image:native-image" from cache
> [INFO]     [creator]     Restoring metadata for "paketo-buildpacks/environment-variables:environment-variables" from app image
> [INFO]     [creator]     Restoring data for "paketo-buildpacks/bellsoft-liberica:native-image-svm" from cache
> [INFO]     [creator]     Restoring data for "paketo-buildpacks/syft:syft" from cache
> [INFO]     [creator]     Restoring data for "paketo-buildpacks/native-image:native-image" from cache
> [INFO]     [creator]     Restoring data for SBOM from cache
> [INFO]     [creator]     ===> BUILDING
> 
> skip...
> 
> [INFO]     [creator]     Paketo Buildpack for Environment Variables 4.5.3
> [INFO]     [creator]       https://github.com/paketo-buildpacks/environment-variables
> [INFO]     [creator]       Launch Configuration:
> [INFO]     [creator]         $BPE_<NAME>                 prepend value to $NAME, delimiting with OS path list separator
> [INFO]     [creator]         $BPE_APPEND_<NAME>          append value to $NAME
> [INFO]     [creator]         $BPE_DEFAULT_<NAME>         set default value for $NAME
> [INFO]     [creator]         $BPE_DELIM_<NAME>           set delimeter to use when appending or prepending to $NAME
> [INFO]     [creator]         $BPE_OVERRIDE_<NAME>        set $NAME to value
> [INFO]     [creator]         $BPE_PREPEND_<NAME>         prepend value to $NAME
> [INFO]     [creator]       Environment Variables: Contributing to layer
> [INFO]     [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.append
> [INFO]     [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.delim
> [INFO]     [creator]         Writing env.launch/LANG
> [INFO]     [creator]         Writing env.launch/LANGUAGE
> [INFO]     [creator]         Writing env.launch/LC_ALL
> [INFO]     [creator]         Writing env.launch/LC_CTYPE
> [INFO]     [creator]     ===> EXPORTING

run:

`docker run -it -e LANG=en_US.utf8 -p 9876:9876 authorization-server:1.0-SNAPSHOT`

> Locale -> it_IT, Country name -> Cina
> Locale -> fr_FR, Country name -> Chine
> Locale -> en_US, Country name -> China
> Locale -> zh_CN, Country name -> ??

I've been stuck with this issue for a week, what should I do?

**Comment by GeTOUO** [comment]
And list some other cases or related solutions that I have already referenced：

https://paketo.io/docs/howto/configuration/#configuring-locale

https://stackoverflow.com/questions/71699595/how-to-change-docker-image-built-with-spring-boot-maven-plugin-env-from-posix-to/71710785

https://stackoverflow.com/questions/65524052/how-can-the-locale-and-encoding-set-in-cloudfoundry-buildpack-docker-image-built

https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Resources/#java-vm-mode-of-localization

https://docs.oracle.com/javase/tutorial/i18n/locale/matching.html


I tried and didn't solve my problem.

**Comment by GeTOUO** [comment]
After countless attempts, I solved the problem like this:
![image](https://github.com/paketo-buildpacks/spring-boot/assets/26786920/8b183ef3-de9a-4406-a7e6-7f56b384fb31)

I'm curious why the parameters can't be passed inside the program, encoding is required:

```
System.setOut(new PrintStream(System.out, true, StandardCharsets.UTF_8));
System.setErr(new PrintStream(System.err, true, StandardCharsets.UTF_8));
```

I also tried these settings and the console never output Chinese:

```
        System.setProperty("file.encoding", "UTF-8"); // Unable to output Chinese
        System.setProperty("sun.jnu.encoding", "UTF-8"); // Unable to output Chinese
        System.setProperty("native.encoding", "UTF-8"); // Unable to output Chinese
        System.setProperty("user.country", "US"); // or CN， Unable to output Chinese
        System.setProperty("user.language", "en"); // or zh， Unable to output Chinese
        Locale.setDefault(Locale.SIMPLIFIED_CHINESE); // Unable to output Chinese
```

**Comment by dmikusa** [comment]
I'm not really sure, beyond what is here https://paketo.io/docs/howto/configuration/#configuring-locale.

1. I see that you're using GraalVM, so try using a non-native image build. Things might differ with GraalVM.

2. Specify system properties via `JAVA_TOOL_OPTIONS`. This will ensure they are all set when the JVM starts before anything loads into memory. When you set them in code with `System.setProperty` results may vary because some resources are only initialized once during the JVM's lifetime and if you set it after it's initialized then it won't actually use that setting.

3. Check that your code works locally outside of buildpacks in a Linux environment. The easiest way is to do something like `docker run` an `ubuntu:jammy` image, followed by installing SDKMAN and the same JVM vendor/version you're trying to use with buildpacks. This will allow you to see what does and doesn't work in an environment that is very similar to what buildpacks install but it's separate so it would rule out potential buildpack configuration/setup issues. Like if the JVM or container is missing something (I don't think this is the case based on your fix, but just being thorough).

4. Look at upstream JVM docs/GraalVM docs because this seems more like an issue with how those tools work than with buildpacks. Especially, if you're able to isolate the issue and reproduce when using a non-buildpacks container, like 3.).

**Comment by GeTOUO** [comment]
Thanks to @dmikusa's advice, my code is working fine at the moment, although I don't know exactly why I need such a cumbersome, maybe the built OCI image I ran directly, but I'll try more later and refer to more upstream documentation.

The following settings in the java code allow System.out to output Chinese normally:

```
System.setOut(new PrintStream(System.out, true, charset));
System.setErr(new PrintStream(System.err, true, charset));
```

The following settings in the pom .xml allow Log to output Chinese normally:

```
<BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
    <!-- -H:+IncludeAllLocales-->
    -Duser.country=CN
    -Duser.language=zh
    -Dfile.encoding=UTF-8
    -Dsun.jnu.encoding=UTF-8
    -Dnative.encoding=UTF-8
    -H:IncludeLocales=zh,fr,en,it
    -H:+AddAllCharsets
</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
```

**Comment by dmikusa** [comment]
Thanks for sharing your solution!
