### ISSUE TITLE
Enforce SB 2.x Upgrades from 1.x

### ISSUE THREAD

**Issue by ktpv** [paketo-buildpacks/spring-boot#4]
Spring Boot 1.x is now EOL and it's been almost two years since the initial warning was issued.
https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019

As of now, SB 2.3 is the current GA version.

I suggest adding a feature to detect a SB 1.x app and throw a warning like "SB 1.x is now EOL, consider upgrading to SB 2.x" and then link to  https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

To make it current by default, the buildpack should maintain a deny list and error out if an old SB version has been detected.  If compatibility with 1.x needs to be maintained, then allowing a user to set an environment variable to override the BP and use older versions, could be offered as long as the warnings above are also issued.

**Comment by nebhale** [comment]
I've been talking with the Spring teams and there's currently an effort to create an automated repository of all open source and commercial support commitments.  We'll use this information to warn (not fail) builds that are using versions that are out of support.

**Comment by nebhale** [comment]
Implemented with the following UX:

### Open Source
![open-source](https://user-images.githubusercontent.com/60754/85880671-44c31d00-b791-11ea-9af1-2ea099128d88.png)

### Commercial
![commercial](https://user-images.githubusercontent.com/60754/85880700-4f7db200-b791-11ea-9171-0b9b0bfd96b1.png)

**Comment by ktpv** [comment]
This is great!
