### ISSUE TITLE
JDK 21 not support

### ISSUE THREAD

**Issue by petercheon** [paketo-buildpacks/spring-boot#410]
## Expected Behavior
build image success

## Current Behavior
i'm using springboot gradle plugin,
When using Paketo Buildpack with Java 21, the following error occurs.
```bash
....
  [creator]         Using Java version 21 from BP_JVM_VERSION
    [creator]       No valid JRE available, providing matching JDK instead. Using a JDK at runtime has security implications.
    [creator]        : Contributing to layer
    [creator]       Warning: Dependency has no SHA256. Skipping cache.
    [creator]         Downloading from 
    [creator]     unable to invoke layer creator
    [creator]     unable to get dependency 
    [creator]     unable to download 
    [creator]     unable to request 
    [creator]     Get "": unsupported protocol scheme ""
    [creator]     ERROR: failed to build: exit status 1
...
```

## Possible Solution
i don't know 

## Steps to Reproduce
i'm using JDK 21 and springboot 3.1.4 with gradle, and run command.
```
./gradlew bootBuildImage
```

## Motivations
i want to use jdk 21 with buildpack.
thank you.

**Comment by scottfrederick** [comment]
Thanks for getting in touch. To get full support for Java 21 with the Paketo buildpacks, you should configure your Gradle build to use the latest Ubuntu 22.04 based builder, as [suggested in a recent blog post](https://spring.io/blog/2023/09/22/paketo-buildpacks-bionic-end-of-support). 

If that doesn't fix your problem, please provide a complete minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it and attaching it to this issue.

**Comment by petercheon** [comment]
Thanks, I have confirmed that it runs successfully based on the information you provided. 👍
