### ISSUE TITLE
Investigate if we can auto-generate CDS archives for Spring apps

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/spring-boot#423]
## Describe the Enhancement

Spring has support that should make it fairly straightforward to generate a CDS archive for a Spring app. It would be a nice feature if the buildpack could automatically run the app, generate the CDS archive, and store it in a layer in the image. There are a few requirements for CDS archives to be effective, see [this article](https://spring.io/blog/2023/12/04/cds-with-spring-framework-6-1), and we also have to ensure that the classpath doesn't change between when the CDS archive is generated and when the app is run.

## Possible Solution

Off the top of my head, it seems like we should be able to run the user's app with the `-Dspring.context.exit=onRefresh` flag, which tells the app to initialize but not start any beans. Then take the CDS archive and put it into a layer. They layer can be cached on the classpath. If the classpath changes, then regenerate the CDS archive.

## Motivation

Start up speed. Apps that have CDS enabled start quite a bit faster than apps without it, and if we can automatically generate the CDS archive for most apps, then that's a free start-up speed increase without any work for the user.

**Comment by dmikusa** [comment]
It seems like we should be able to do the same thing with Crac and Spring Boot 3.2+.

At build time we can run, take the snapshot and the store that as an app layer.

**Comment by anthonydahanne** [comment]
here is the PR implementing it: https://github.com/paketo-buildpacks/spring-boot/pull/427
