### ISSUE TITLE
Broken detection logic on non-spring projects

### ISSUE THREAD

**Issue by modulo11** [paketo-buildpacks/spring-boot#474]
## Expected Behavior

The buildpack should not kick in for non Spring-Boot apps.

## Current Behavior

Building the [war](https://github.com/paketo-buildpacks/samples/tree/main/java/war) sample using 

```
pack build --clear-cache --builder paketobuildpacks/builder-jammy-base --env BP_JVM_VERSION=11 --buildpack gcr.io/paketo-buildpacks/java:13.0.0 sample-war
```

currently fails with 

```
Paketo Buildpack for Spring Boot 5.29.0
  unable to find Spring Boot Executable Jar
  open : no such file or directory
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

## Possible Solution

The [logic](https://github.com/paketo-buildpacks/spring-boot/blob/f842af4a21c9b8acd26979cba6e834776d6d6a5a/boot/build.go#L69-L80) seems to be complicated and probably needs an [early return](https://github.com/paketo-buildpacks/spring-boot/blob/7944296ccb7ecefd2ef5da13cd83f48269ea60ff/boot/build.go#L59-L63) if the app is not using spring-boot.

## Steps to Reproduce

1. Clone samples
2. Run `pack build` using the latest release

**Comment by dmikusa** [comment]
Acknowledged. @paketo-buildpacks/java-maintainers  looking into it.
