### ISSUE TITLE
native_image.go doesn't include META-INF on classpath

### ISSUE THREAD

**Issue by dsyer** [paketo-buildpacks/spring-boot#5]
The GraalVM native-image tooling looks in `/META-INF/native-image` for JSON configuration, but the buildpack doesn't include that on the classpath (it only takes entries from `BOOT-INF/lib` per the manifest). The result is that you either can't build an image, or it fails at runtime because it can't find resources that were configure there.

**Comment by nebhale** [comment]
Resolved by 6eb80c1d284b944b29a8b63d7123247da706acf5
