### ISSUE TITLE
Environment and dependency mapping not taken into account

### ISSUE THREAD

**Issue by FredPraca** [paketo-buildpacks/spring-boot#518]
I'm using a _Gitlab_ runner in an isolated network environment.
The only way to download things is through a Nexus proxy.

For _BellSoft Liberica JDK/JRE_ and _Syft_, I was able to use the dependency mirror bindings.
When it comes to _Spring Cloud Bindings_, I tested with a dependency mapping binding but it does not seem to be taken into account.

I currently use the following CI job script:

  ```
    - export PLATFORM_PATH=src/main/resources/platform
    - mkdir -p $PLATFORM_PATH/env
    # Environment variables
    - echo $CI_DEPLOY_PASSWORD > $PLATFORM_PATH/env/CI_DEPLOY_PASSWORD
    # Define Java version
    - echo 21 > $PLATFORM_PATH/env/BP_JVM_VERSION
    # Remove Spring cloud bindings
    - echo true > $PLATFORM_PATH/env/BP_SPRING_CLOUD_BINDINGS_DISABLED
    - echo true > $PLATFORM_PATH/env/BPL_SPRING_CLOUD_BINDINGS_DISABLED
    - echo false > $PLATFORM_PATH/env/BPL_SPRING_CLOUD_BINDINGS_ENABLED
    # Prepare bindings
    # Mappings
    # Add specific mirror for cloud-bindings
    - mkdir -p $PLATFORM_PATH/bindings/dependency-mapping/
    - echo https://nexus.example.com/repository/maven-group/org/springframework/cloud/spring-cloud-bindings/2.0.3/spring-cloud-bindings-2.0.3.jar > $PLATFORM_PATH/bindings/dependency-mapping/0390f964e9cadbb0795f44b2b29d2e6755bd8b800a94fee980aed8c26766c124
    - echo dependency-mapping > $PLATFORM_PATH/bindings/dependency-mapping/type
    # Mirrors
    - mkdir -p $PLATFORM_PATH/bindings/dependency-mirror
    - echo https://nexus.example.com/repository/maven-group > $PLATFORM_PATH/bindings/dependency-mirror/default
    - echo https://nexus.example.com/repository/github-raw > $PLATFORM_PATH/bindings/dependency-mirror/github.com
    - echo https://nexus.example.com/repository/bell-sw > $PLATFORM_PATH/bindings/dependency-mirror/download.bell-sw.com
    - echo dependency-mirror > $PLATFORM_PATH/bindings/dependency-mirror/type
    # Authentication to retrieve preexisting image
    - mkdir ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" >> ~/.docker/config.json
    - export CNB_PLATFORM_API=0.14
    - export CNB_INSECURE_REGISTRIES="nexus.example.com:5000"
    - export CNB_RUN_IMAGE=nexus.example.com:5000/paketobuildpacks/run-jammy-tiny:latest
    - /cnb/lifecycle/creator -app . -platform $PLATFORM_PATH $CI_REGISTRY_IMAGE:latest
```

As a result, I get this

```
Paketo Buildpack for Spring Boot 5.31.2
  https://github.com/paketo-buildpacks/spring-boot
  Build Configuration:
    $BPL_JVM_CDS_ENABLED                 false  whether to enable CDS optimizations at runtime
    $BPL_SPRING_AOT_ENABLED              false  whether to enable Spring AOT at runtime
    $BP_JVM_CDS_ENABLED                  false  whether to enable CDS & perform JVM training run
    $BP_SPRING_AOT_ENABLED               false  whether to enable Spring AOT
    $BP_SPRING_CLOUD_BINDINGS_DISABLED   false  whether to contribute Spring Boot cloud bindings support
    $BP_SPRING_CLOUD_BINDINGS_VERSION    1      default version of Spring Cloud Bindings library to contribute
  Launch Configuration:
    $BPL_SPRING_CLOUD_BINDINGS_DISABLED  false  whether to auto-configure Spring Boot environment properties from bindings
    $BPL_SPRING_CLOUD_BINDINGS_ENABLED   true   Deprecated - whether to auto-configure Spring Boot environment properties from bindings
  Creating slices from layers index
    dependencies (117.6 MB)
    spring-boot-loader (399.5 KB)
    snapshot-dependencies (57.1 KB)
    application (9.1 MB)
  Spring Cloud Bindings 2.0.3: Contributing to layer
    Downloading from https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-bindings/2.0.3/spring-cloud-bindings-2.0.3.jar
unable to invoke layer creator
unable to contribute spring-cloud-bindings layer
unable to get dependency Spring Cloud Bindings. see DEBUG log level
ERROR: failed to build: exit status 1
Cleaning up project directory and file based variables
```

Environment variables seem to have be ignored as well as my mapping.

## Expected Behavior
Downloading should be done through my Nexus proxy or Spring Cloud bindings should be disabled according to environment.

## Current Behavior
Buildpack goes on downloading from _repo1.maven.org_

## Steps to Reproduce

This might be hard.

1. Close every outgoing requests to _repo1.maven.org_
2. Setup a Nexus proxy or reverse proxy to serve _repo1.maven.org_
3. Prepare a simple Spring Boot application with the configuration mentioned in the first part

**Comment by dmikusa** [comment]
Anything downloaded by the buildpack itself, such as Spring Cloud Bindings JAR or the JVM itself, is all downloaded with the same code. There shouldn't be any difference in behavior.

There are a number of things that need to line up for dependency mappings to work, they can be a little finicky. The [`binding-tool` cli](https://github.com/dmikusa/binding-tool) can help to get these correct. You could try generating the bindings with that and comparing to what you're generating. If you want to use the binding approach. 

You are also configuring a mirror though, so I would suggest just using that approach. If you want to use both, the binding will take precedent and you'll see this message.

> Both dependency mirror and bindings are present. %s Please remove dependency map bindings if you wish to use the mirror.

The fact that it's not showing that message makes me think something is off with one or both of the configurations. Probably both, because you should see a message that says `Dependency mirror found.` if the buildpack detects your mirror configuration.

It is a little tricky for me to tell what might be wrong with the configuration given the way you're running the application build (I don't personally use Gitlab CI, sorry). Maybe try getting it to work with `pack build` first and then try this approach? Once you have working bindings, you can copy them and ensure they're the same in your CI. You can also configure your mirror with env variables, instead of bindings, if that approach is easier.

Hope that helps!

**Comment by FredPraca** [comment]
Thanks for your help.

I finally figured out what was going on.
For the record, when using _Gitlab-CI_, you land inside the building directory where the source is.
I was creating the platform files inside it which was ok until _maven_ buildpack cleared the source directory, including every platform files I created.

After clearing, as no configuration is kept, following buildpacks don't have the customization anymore.

Thanks for replying me so fast and for the work done here.

**Comment by dmikusa** [comment]
> The problem here is that mirrors, as far as I understood, expect the whole hierarchy to be mirrored.
At this time, I've used it for Github but I'm not that happy to mirror the whole Github site to the protected network.
Mirroring sub-hierarchies would be great.

You have a choice. It will go to the mirror for everything, but you don't have to have everything on your mirror. If there are things you don't want to be available, you can control that by simply not putting them in the mirror. If someone tries to do a build and use a resource that's unavailable through the mirror then that build will fail.

**Comment by FredPraca** [comment]
In fact, my mirror is not a mirror but a proxy.
That's the reason why I pointed it out.
