### ISSUE TITLE
spring-cloud-bindings-1.7.1.jar: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by tummalah** [paketo-buildpacks/spring-boot#81]
## What happened?
Trying to Build image through Paketo Buildpack for Spring Boot Application through pack cli

* What were you attempting to do?
pack build --builder=paketobuildpacks/builder:base myorg-docker.jfrog.io/ar-invoices-test:latest --env BPL_SPRING_CLOUD_BINDINGS_ENABLED=false

* What was the actual behavior? Please provide log output, if possible.
condensed
```
Paketo Spring Boot Buildpack 4.2.0

  https://github.com/paketo-buildpacks/spring-boot

  Launch Helper: Contributing to layer

    Creating /layers/paketo-buildpacks_spring-boot/helper/exec.d/spring-cloud-bindings

  Spring Cloud Bindings 1.7.1: Contributing to layer

    Downloading from https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar

unable to invoke layer creator

unable to contribute spring-cloud-bindings layer

unable to get dependency spring-cloud-bindings

unable to download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar

unable to request https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar

Get "https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar": x509: certificate signed by unknown authority

ERROR: failed to build: exit status 1

ERROR: failed to build: executing lifecycle: failed with status code: 145
```
## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? 
pack version 0.18.0

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
paketobuildpacks/builder:base

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
>Get "https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar": x509: certificate signed by unknown authority

This error shouldn't happen. It means you're trying to connect to our repo, but the TLS certificate isn't right (i.e. it's not actually our service). Are you behind a proxy or corporate firewall? Many companies rewrite TLS certificates so they can spy on the traffic. If you're unsure, go to https://repo.spring.io in your browser (your browser probably has the corp certificate installed already, click on the lock and view the server certificates. You should see the following, if not then something is changing the certificates.

<img width="524" alt="Screen Shot 2021-05-11 at 8 12 02 PM" src="https://user-images.githubusercontent.com/4643262/117899511-45737d80-b295-11eb-93a9-53a2451d8a64.png">

If that is the case, you will need to get a copy of the Root CA certificate your company is using (you can download this from your browser) and add that to the build containers. You can do that with the ca-certificates buildpack and by following instructions: https://paketo.io/docs/buildpacks/configuration/#ca-certificates.

Hope that helps!

**Comment by tummalah** [comment]
@dmikusa-pivotal  Thank you and yes that is what is happening. I will try the ca-certificates build pack and get back.

**Comment by tummalah** [comment]
@dmikusa-pivotal  using ca-certificates binding has fixed the issue. Thanks a ton 👍

**Comment by dmikusa-pivotal** [comment]
Fantastic!

**Comment by mancave** [comment]
Can we disable this check during build time, just like the BP_ENABLE_RUNTIME_CERT_BINDING(https://paketo.io/docs/buildpacks/configuration/#ca-certificates) setting

**Comment by dmikusa-pivotal** [comment]
@mancave if you are behind a proxy that is manipulating certificates, then you need to follow the instructions I posted above.

https://github.com/paketo-buildpacks/spring-boot/issues/81#issuecomment-839317809

You can't just disable this. It's the purpose of TLS to tell you when someone is manipulating the certificates & prevent man-in-the-middle attacks. Your company's proxy is a man-in-the-middle, hence the error. You need to add the CA certificate for your proxy so that it can be properly trusted.

**Comment by mancave** [comment]
It's getting overcomplex, I'm running in a CICD(GitLab) configuration with docker and using the maven build for the springboot application. How can I configure the maven spring-boot-maven-plugin to handle this certificates in one go ?
